### ISSUE TITLE
Is it possible to return all materials when we use "materials function" ?

### ISSUE THREAD

**Issue by teramonagi** [uribo/Japan.useR#1]
Hi uribo-san;

Thank you for making a great package.
I have one suggestion for this.

Is it possible to return all materials when we use "materials function" for specified community?
It will be very useful for us when we handle all historical data.

You just need to remove "head" function like the following:
from 

```
return(head(res)) # Community だけを指定
```

to

```
return(res) # Community だけを指定
```

**Comment by uribo** [comment]
Thanks for comments.

Please reopen it if you have any further comments.
